cask_args appdir: "/Applications"

tap "caskroom/cask"
tap "telemachus/brew", "https://telemachus@bitbucket.org/telemachus/brew.git"

brew "git"
brew "go"
brew "nvm"
brew "peco"
brew "rbenv"
brew "vim"
brew "zsh"
brew "ghq"

cask "appcleaner"
cask "calibre"
cask "cooviewer"
cask "google-chrome"
cask "kindle"
cask "macvim"
cask "the-unarchiver"
cask "transmission"
cask "vlc"
cask "visual-studio-code"
